### ISSUE TITLE
Tweaks for blog etc.

### ISSUE THREAD

**Issue by jjeffryes** [OB1Company/haven_website_new#9]
https://app.zeplin.io/project/5ce5cc45c010891e5fe039be/screen/5ceff78b86ef376f60040a25?did=5ceff9561f5a851e118e7e74&cmid=5ceff9561f5a851e118e7e75&ref=slack

please replace this sharp grey line with a soft gradient from grey>white. Can be real subtle spanning anywhere from 400-600px for the transition.

Same design change for the main blog page too

https://app.zeplin.io/project/5ce5cc45c010891e5fe039be/screen/5ceff7696801a41be3599a96?did=5ceff9ba35e83a1d567893f6&cmid=5ceff9ba35e83a1d567893f7&ref=slack

Please replace this sharp grey line with a soft gradient from grey>white. Can be real subtle spanning anywhere from 350-600px for the transition.

Should probably start 200px higher too, somewhere around the bottom of the page title so it looks a bit like a header bar.

https://app.zeplin.io/project/5ce5cc45c010891e5fe039be/screen/5cee4e807a42a54535044150?did=5ceff58e5d01801e1ccf82ec&cmid=5ceff58e5d01801e1ccf82ed&ref=slack

please shift this green shape back 40px to let this headline and button breathe a bit more.

https://app.zeplin.io/project/5ce5cc45c010891e5fe039be/screen/5cee4e807a42a54535044150?did=5ceff5f34c7fea1d62e82777&cmid=5ceff5f34c7fea1d62e82778&ref=slack

Let's center vertically the text and icon to the box, or decrease the height so there's less white space at the bottom here.

https://app.zeplin.io/project/5ce5cc45c010891e5fe039be/screen/5cee4e6e8f23d01d86715bf9?did=5ceff6463dd1771d98d7b4c1&cmid=5ceff6463dd1771d98d7b4c2&ref=slack

Super pedantic but if these boxes could have the same padding in relation to screen size as the three main header boxes above that'd be rad.

needs like 10% more padding each side.

**Comment by jenncloud** [comment]
Center image captions

Adjust H3 size - it's currently smaller than H4

Treatment for longer quotes that don't look as good in the large, italic typeface?

**Comment by jjeffryes** [comment]
These are all complete.

The grey gradient for the blog and other pages is very subtle, I'm not positive that's exactly what was being requested, but it's easy to change.
